version: 2.1

definitions:
  release_filters: &release_filters
    branches:
      only: master
    tags:
      only: /.*/
  multi_hash_args: &multi_hash_args
    in-files: "build.sbt project/build.properties project/plugins.sbt"
    out-file: /tmp/sbt-dependencies-checksum
    cache-prefix: sbt-sentry
  cache_name: &cache_name sbt-sentry-{{ checksum "/tmp/sbt-dependencies-checksum" }}-{{ .Branch }}
  aws_auth: &aws_auth
    aws_access_key_id: $AWS_ACCESS_KEY_ID
    aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
  scala_version: &scala_version 2.12.6
  step_aliases:
    # Add ssh key used to clone cobli-sbt-settings
    - &ssh_setup
      add_ssh_keys:
        fingerprints:
          - "c7:17:f9:43:b3:5b:49:42:74:dd:f5:8a:74:d3:98:e3"

orbs:
  multi_file_hash_cache: cobli/multi-file-hash-cache@0.0.2

jobs:
  publish:
    docker:
      - image: circleci/openjdk:8u222-jdk-stretch
    environment:
      TERM: xterm-256color
      SCALA_VERSION: *scala_version
    steps:
      - checkout
      - *ssh_setup
      - multi_file_hash_cache/restore:
          <<: *multi_hash_args
      - run:
          name: Create and publish package to S3
          command: sbt ++$SCALA_VERSION publish
      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.sbt/boot
            - ~/.cache/coursier
          key: *cache_name

workflows:
  publish:
    jobs:
      - publish:
          name: publish_to_s3
          context: circleci-aws-profile
          filters:
            <<: *release_filters
